import os, sys
os.system('clear')
os.system('rm update.py')
os.system('rm useragent.txt')
os.system('rm main.py')
os.system('rm README.md')
os.system('clear')
kontol = input('dah gitu aja, gausah nanya kenapa\nkok error, kok gabisa, kok rusak. Mikir sendiri.\n\n)
if kontol in ['',' ']:os.system('xdg-open https://www.facebook.com/bagasekaapr');exit()
else:os.system('xdg-open https://www.facebook.com/bagasekaapr');exit()
